# Generated by Django 4.0 on 2022-02-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='packagedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('slct1', models.CharField(max_length=100)),
                ('slct2', models.CharField(max_length=100)),
                ('city1', models.CharField(max_length=100)),
                ('pincode1', models.IntegerField()),
                ('state1', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('city2', models.CharField(max_length=100)),
                ('pincode2', models.IntegerField()),
                ('state2', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('accept', models.CharField(blank=True, default='Order accepted', max_length=100)),
                ('pickup', models.CharField(blank=True, default='Order picked up from pickup', max_length=100)),
                ('left', models.CharField(blank=True, default='Order left for drop city', max_length=100)),
                ('reach', models.CharField(blank=True, default='Order reached drop city', max_length=100)),
                ('shipped', models.CharField(blank=True, default='Order shipped successfully', max_length=100)),
            ],
        ),
    ]
