# Generated by Django 4.0 on 2022-02-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='track_id',
            field=models.TextField(default='1151195'),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='accept',
            field=models.CharField(blank=True, choices=[('Order Pending', '-'), ('Order Accepted', 'Order Accepted')], default='Order Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='left',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Package Left For Drop City', 'Package Left For Drop City')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='pickup',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Package Picked Up', 'Package Picked Up')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='reach',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Package Reached Drop City', 'Package Reached Drop City')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='shipped',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Package Delivered Successfully ', 'Package Delivered Successfully ')], default='-', max_length=100),
        ),
    ]
