# Generated by Django 4.0 on 2022-02-19 18:54

import details.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('details', '0002_packagedetails_track_id_alter_packagedetails_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='track_id',
            field=models.TextField(blank=True, default=details.models.random_string),
        ),
    ]
