# Generated by Django 4.0 on 2022-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('dob', models.IntegerField()),
                ('empstatus', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
